table:
  schema: public
  name: deployment
configuration:
  custom_root_fields: {}
  custom_column_names:
    updated_at: updatedAt
    created_at: createdAt
array_relationships:
  - name: admin_structures
    using:
      foreign_key_constraint_on:
        column: deployment_id
        table:
          schema: public
          name: admin_structure
  - name: beneficiaries
    using:
      foreign_key_constraint_on:
        column: deployment_id
        table:
          schema: public
          name: beneficiary
  - name: managers
    using:
      foreign_key_constraint_on:
        column: deployment_id
        table:
          schema: public
          name: manager
  - name: structures
    using:
      foreign_key_constraint_on:
        column: deployment_id
        table:
          schema: public
          name: structure
insert_permissions:
  - role: admin_cdb
    permission:
      check: {}
      columns:
        - id
        - label
        - created_at
        - updated_at
        - config
      backend_only: false
select_permissions:
  - role: admin_cdb
    permission:
      columns:
        - label
        - config
        - created_at
        - updated_at
        - id
      filter: {}
      allow_aggregations: true
  - role: admin_structure
    permission:
      columns:
        - created_at
        - id
        - label
        - updated_at
      filter:
        id:
          _eq: X-Hasura-Deployment-Id
      allow_aggregations: true
  - role: manager
    permission:
      columns:
        - config
        - created_at
        - id
        - label
        - updated_at
      filter:
        id:
          _eq: X-Hasura-Deployment-Id
      allow_aggregations: true
  - role: professional
    permission:
      columns:
        - created_at
        - id
        - label
        - updated_at
      filter:
        id:
          _eq: X-Hasura-Deployment-Id
      allow_aggregations: true
update_permissions:
  - role: admin_cdb
    permission:
      columns:
        - label
        - config
        - created_at
        - updated_at
        - id
      filter: {}
      check: {}
