table:
  name: deployment
  schema: public
configuration:
  custom_column_names:
    created_at: createdAt
    updated_at: updatedAt
  custom_root_fields: {}
array_relationships:
- name: admin_structures
  using:
    foreign_key_constraint_on:
      column: deployment_id
      table:
        name: admin_structure
        schema: public
- name: beneficiaries
  using:
    foreign_key_constraint_on:
      column: deployment_id
      table:
        name: beneficiary
        schema: public
- name: managers
  using:
    foreign_key_constraint_on:
      column: deployment_id
      table:
        name: manager
        schema: public
- name: structures
  using:
    foreign_key_constraint_on:
      column: deployment_id
      table:
        name: structure
        schema: public
insert_permissions:
- permission:
    backend_only: false
    check: {}
    columns:
    - id
    - label
    - created_at
    - updated_at
    - config
  role: admin_cdb
select_permissions:
- permission:
    allow_aggregations: true
    columns:
    - label
    - config
    - created_at
    - updated_at
    - id
    filter: {}
  role: admin_cdb
- permission:
    allow_aggregations: true
    columns:
    - label
    - config
    - created_at
    - updated_at
    - id
    filter:
      id:
        _eq: X-Hasura-Deployment-Id
  role: manager
update_permissions:
- permission:
    check: {}
    columns:
    - label
    - config
    - created_at
    - updated_at
    - id
    filter: {}
  role: admin_cdb
