kind: ConfigMap
apiVersion: v1
metadata:
  name: app-configmap
data:
  SMTP_HOST: smtp.mailtrap.io
  SMTP_PORT: '2525'
  SMTP_FROM: support.carnet-de-bord@fabrique.social.gouv.fr
  API_PARTICULIER_URL: https://particulier-test.api.gouv.fr/api
  SANDBOX_LOGIN: 'true'
