app:
  envFrom:
    - secretRef:
        name: pg-user-{{ .Values.global.branchSlug }}
    - secretRef:
        name: app-sealed-secret
    - configMapRef:
        name: app-configmap

hasura:
  needs: [seed]
  envFrom:
    - secretRef:
        name: pg-user-{{ .Values.global.branchSlug }}
    - secretRef:
        name: hasura-sealed-secret
    - configMapRef:
        name: hasura-configmap

app-api:
  envFrom:
    - secretRef:
        name: app-sealed-secret
    - configMapRef:
        name: app-configmap

jobs:
  enabled: true
  runs:
    - name: db
      use: SocialGouv/kube-workflow/jobs/create-db
      with:
        pgAdminSecretRefName: azure-pg-admin-user
    - name: seed
      needs: [db]
      use: SocialGouv/kube-workflow/jobs/seed-db@seed
      with:
        seedPath: hasura/seeds/carnet_de_bord/seed-data.sql
