name: Deactivate

on:
  pull_request:
    types: [ closed ]
    
jobs:

  deactivate:
    name: Deactivate review branch
    runs-on: ubuntu-latest
    steps:

    - uses: SocialGouv/actions/k8s-deactivate@master
      with:
        kube-config: ${{ secrets.SOCIALGOUV_KUBE_CONFIG_DEV2  }}
