name: Lint

on: push

concurrency:
  cancel-in-progress: true
  group: lint-${{ github.ref }}

jobs:
  ##############################################################################
  ## Full linting/checking running on all branches
  ##############################################################################
  lint:
    name: run full linting on project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Yarn cache setup
        uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: |
          yarn install --prefer-offline --frozen-lockfile
      - name: Install e2e dependencies
        run: |
          yarn --cwd e2e install --prefer-offline --frozen-lockfile
      - name: Run full linting
        run: |
          yarn lint
